package org.hotcode.hotcode;

/**
 * First parameter of the constructor generated by HotCode, to mark the constructor as a HotCode generated constructor.
 * 
 * @author khotyn.huangt 13-7-18 AM9:53
 */
public interface HotCodeGenConstructorMarker {
}
